package dev.romerobrayan.tinto.core.domain.model

/**
 * How a movement entered the ledger. [RECURRING] (Sprint 5) marks a movement
 * generated by a user-created automation rule. Additive — parse the persisted
 * value tolerantly (unknown → MANUAL) so a newer value never drops a row.
 */
enum class TransactionSource { MANUAL, NOTIFICATION, EMAIL, SMS, RECURRING }
